### ISSUE TITLE
Grafana does not find Datasources or Dashboards

### ISSUE THREAD

**Issue by carlosedp** [brancz/kubernetes-grafana#53]
After deploying Grafana with the Kube-prometheus stack, Grafana does not find the Prometheus Datasource or default dashboards.

In it's logs it shows that the provisioning path is `/usr/share/grafana/conf/provisioning`:

```
Pod: grafana-6c4f67b8d8-gpd5m

t=2018-12-07T20:50:26+0000 lvl=info msg="Starting Grafana" logger=server version=5.4.0 commit=69c5191 branch=HEAD compiled=2018-12-03T10:17:42+0000
t=2018-12-07T20:50:26+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2018-12-07T20:50:26+0000 lvl=info msg="Config loaded from" logger=settings file=/grafana/conf/config.ini
t=2018-12-07T20:50:26+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2018-12-07T20:50:26+0000 lvl=info msg="Path Data" logger=settings path=/data
t=2018-12-07T20:50:26+0000 lvl=info msg="Path Logs" logger=settings path=/data/log
t=2018-12-07T20:50:26+0000 lvl=info msg="Path Plugins" logger=settings path=/data/plugins
t=2018-12-07T20:50:26+0000 lvl=info msg="Path Provisioning" logger=settings path=/usr/share/grafana/conf/provisioning
t=2018-12-07T20:50:26+0000 lvl=info msg="App mode production" logger=settings
t=2018-12-07T20:50:26+0000 lvl=info msg="Initializing HTTPServer" logger=server
t=2018-12-07T20:50:26+0000 lvl=info msg="Initializing SqlStore" logger=server
t=2018-12-07T20:50:26+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2018-12-07T20:50:26+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2018-12-07T20:50:26+0000 lvl=info msg="Executing migration" logger=migrator id="create migration_log table"
t=2018-12-07T20:50:26+0000 lvl=info msg="Executing migration" logger=migrator id="create user table"
```

After changing the `manifests/grafana-deployment.yaml` mount points to the correct path, it loaded correctly:

```
...
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
          readOnly: false
        #- mountPath: /etc/grafana/provisioning/datasources
        - mountPath: /usr/share/grafana/conf/provisioning/datasources
          name: grafana-datasources
          readOnly: false
        #- mountPath: /etc/grafana/provisioning/dashboards
        - mountPath: /usr/share/grafana/conf/provisioning/dashboards
          name: grafana-dashboards
          readOnly: false
```

No custom config.ini was used.
